baseURL = "https://lennykiruthu.xyz/"
languageCode = "en-us"
title = "Lenny Kiruthu"
theme = "hugo-theme-stack"

[params]
  description = "Building data systems in public."
  author = "Lenny Kiruthu"
  github = "https://github.com/lennykiruthu"
  email = ""

  [params.sidebar]
    subtitle = "Building data systems in public."
    avatar = "img/pexels-efdal-yildiz-325089-917494.jpg"

[menu]
  [[menu.main]]
    name = "Multi Asset Portfolio Analytics Platform"
    url = "/multi-asset-portfolio-analytics-platform/"
    weight = 1

  [[menu.main]]
    name = "Build Log"
    url = "/building/"
    weight = 2

  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 3

  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/lennykiruthu"
    [menu.social.params]
      icon = "brand-github"
      newTab = true

  [[menu.social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/lenny-kiruthu"
    [menu.social.params]
      icon = "brand-linkedin"
      newTab = true    

[taxonomies]
  tag = "tags"
  project = "project"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    style = "monokai"
    lineNos = false